### ISSUE TITLE
Page broken on openedx.microsoft.com

### ISSUE THREAD

**Issue by TechWatching** [MicrosoftDocs/azure-docs.fr-fr#302] opened 2019-03-16 16:19 UTC
This content is also available as part of a course on openex.microsoft.com. However on the course, part of this content is broken probably due to a code area not correctly closed or closed too soon.

I don't know how do you proceed to make the course on openedx refer to part of the docs.microsoft.com documentation but there are often issues : either the content is not reviewed correctly or the content does not stay up-to-date with the documentation. Too bad, because in themselves courses are great and documentation nice.

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: 6115d555-45a1-6539-4af6-fbc20a99f008
* Version Independent ID: 21f80c83-ba10-9b7e-c54f-51a9c140517c
* Content: [Démarrage rapide : créer un cluster AKS (Azure Kubernetes Service)](https://docs.microsoft.com/fr-fr/azure/aks/kubernetes-walkthrough#feedback)
* Content Source: [articles/aks/kubernetes-walkthrough.md](https://github.com/MicrosoftDocs/azure-docs.fr-fr/blob/live/articles/aks/kubernetes-walkthrough.md)
* Service: **container-service**
* GitHub Login: @iainfoulds
* Microsoft Alias: **iainfou**

**Comment by CeciAc** [comment] 2019-03-18 14:51
Hello, @TechWatching 
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment] 2019-03-18 14:59
Hi @ishasahni1 
I'm assigning this issue to you since the user is reporting an external error.
Please, let me know if I should move this somewhere else
best regards

FYI @DavidPrio

**Comment by ishasahni1** [comment] 2019-03-27 02:56
@TechWatching thank you for the valuable feedback, will try to share your valuable feedback to the team managing content on Opendex.

@CeciAc FYI

**Comment by ishasahni1** [comment] 2019-03-27 02:57
@TechWatching Can you kindly provide us the sample openedex link as an example for quick reference, so we can share the same with team for reference.

@CeciAc

**Comment by TechWatching** [comment] 2019-03-29 08:32
Yes sure. An example of this is the "Microsoft: AZ-200.3 Develop Azure Platform as a Service solutions" course, section "Create solutions that use Azure Kubernetes Service",   part "Creating an Azure Kubernetes Service cluster", page "Deploy an AKS cluster using Azure CLI" on openedx.microsoft.com.

The corresponding link is the following:
https://openedx.microsoft.com/courses/course-v1:Microsoft+AZ-200.3+2019_T1/courseware/5b277772-6b7a-b84e-717e-a250aad165f6/2092e421-2c7a-b723-4650-e51dec31c2a4/1?activate_block_id=block-v1%3AMicrosoft%2BAZ-200.3%2B2019_T1%2Btype%40vertical%2Bblock%4004950f1d-db4a-7156-68e8-b0fa42f801fa

As you can see on the following sreenshot, the yaml file is incorrect, the content continues in the next paragraph:
![image](https://user-images.githubusercontent.com/15186176/55219503-5a9c0800-5205-11e9-8603-5d85c68a5dab.png)

**Comment by CeciAc** [comment] 2019-05-10 20:47
Hi @ishasahni1 
Is this still in progress?

**Comment by ishasahni1** [comment] 2019-05-15 22:25
@TechWatching this feedback has been shared with the team and they confirmed that the fix has been implemented on the site. 

@CeciAc

**Closed by ishasahni1** 2019-05-15 22:25 UTC
Labels: Technical Issue
